---
deployment:
  tasks:
    - export REPOPATH=https://github.com/alex-ermmm/kronos.git
    - export SITEPATH=/home/atestkro/public_html/local/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH