---
deployment:
  tasks:
    - export REPOPATH=/home/public_html/local/*
    - export SITEPATH=/home/public_html/local/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH